// Name: Patrick Morrissey K00218348
// Date: 09/05/2026
// Function: CA3 Encounter Design and Tactical Play

package roguelike;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;


// In order to build better caves with z levels and more depth, we’re going to have to work with coordinates a lot. We should
// make a class to represent a point in space.
public class Point {
    public int x;
    public int y;
    public int z;

    // when regions points are added to a regions list of points using Region addTilePoint(), the regionID is set to ID of the region its being added to
    private int regionID;
    public int regionID() { return regionID; }
    public void setRegionID(int newRegionID) {regionID = newRegionID; }

    public Point(int x, int y, int z) {
        this.x = x;
        this.y = y;
        this.z = z;
        this.regionID = 0;
    }

    // Two points that represent the same location should be treated as equal. We can achieve
    // that by overriding the hashCode and equals methods.
    // A hashcode is an integer generated by a mathematical algorithm that maps an object's data to a specific value
    // converts the point coordinates into a hashcode
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + x;
        result = prime * result + y;
        result = prime * result + z;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof Point))
            return false;
        Point other = (Point) obj; // needed for accessing other.x, other.y, and other.z
        if (x != other.x)
            return false;
        if (y != other.y)
            return false;
        if (z != other.z)
            return false;
        return true;
    }

    // returns a list of a point's 8 neighbours
    public List<Point> neighbors8() {
        List<Point> points = new ArrayList<Point>();
        for (int ox = -1; ox < 2; ox++) {
            for (int oy = -1; oy < 2; oy++) {
                // used for ignoring the current point itself
                if (ox == 0 && oy == 0)
                    continue;
                int nx = x + ox;
                int ny = y + oy;
                points.add(new Point(nx, ny, z));
            }
        }
        Collections.shuffle(points); // shuffle the list before returning it so we don’t introduce bias
        // Otherwise the upper left neighbour would always be checked first and the lower right would be last which may lead to some odd things.
        return points;
    }

    // returns the tile at the position the point represents
    public Tile getPointTile(Tile[][][] tiles)
    {
        return tiles[x][y][z];
    }

    public int distanceBetweenPoints(int xR1, int yR1, int xR2, int yR2)
    {
        int distX = xR2 - xR1;
        int distY = yR2 - yR1;

        double distance = Math.sqrt((distX * distX) + (distY * distY));

        return (int)distance;
    }
}
